### ISSUE TITLE
haven.launcher.ValidationException: Could not validate https://enderwiggin.github.io/hafen/hafen.hl

### ISSUE THREAD

**Issue by Marabellia** [EnderWiggin/hafen-client#116]
Hello, upon launching Haven and Hearth, I receive the above error and crash.

Copy-paste of full launcher error popup:

```
haven.launcher.ValidationException: Could not validate https://enderwiggin.github.io/hafen/hafen.hl
 	at haven.launcher.Resource.validate(Resource.java:61)
 	at haven.launcher.Resource.update(Resource.java:84)
 	at haven.launcher.Driver.run(Driver.java:53)
 	at haven.launcher.Driver.main(Driver.java:144)
 	Suppressed: haven.launcher.ValidationException: file not downloaded over tls connection signed with key:rsa:2FA041AE61200B512AC79637E88FD833E31BC8BC7D56E6417B3D3CC14B486392
 		at haven.launcher.Validator$TlsKeyValidator.validate(Validator.java:43)
 		at haven.launcher.Resource.validate(Resource.java:55)
 		... 3 more
```

Full copy paste of the error.log file:

```
haven.Resource$LoadFailedException: Failed to load resource gfx/invobjs/bogturtle-cleaned (v1)
	at haven.Resource$Pool$Queued.get(Resource.java:559)
	at haven.Resource$Pool$Queued.get(Resource.java:526)
	at haven.Session$CachedRes$Ref.get(Session.java:139)
	at haven.Session$CachedRes$Ref.get(Session.java:130)
	at haven.GItem.spr(GItem.java:181)
	at haven.WItem.draw(WItem.java:299)
	at haven.Widget.draw(Widget.java:784)
	at haven.Widget.draw(Widget.java:789)
	at haven.Inventory.draw(Inventory.java:108)
	at haven.Widget.draw(Widget.java:784)
	at haven.Widget.draw(Widget.java:789)
	at haven.Widget.draw(Widget.java:784)
	at haven.Widget.draw(Widget.java:789)
	at haven.Widget.draw(Widget.java:784)
	at haven.Widget.draw(Widget.java:789)
	at haven.GameUI.draw(GameUI.java:1283)
	at haven.Widget.draw(Widget.java:784)
	at haven.Widget.draw(Widget.java:789)
	at haven.RootWidget.draw(RootWidget.java:121)
	at haven.UI.draw(UI.java:397)
	at haven.GLPanel$Loop.display(GLPanel.java:311)
	at haven.GLPanel$Loop.run(GLPanel.java:400)
	at haven.JOGLPanel.run(JOGLPanel.java:246)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource gfx/invobjs/bogturtle-cleaned(v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/res/)
	at haven.Resource$Pool.handle(Resource.java:619)
	at haven.Resource$Pool.access$1200(Resource.java:503)
	at haven.Resource$Pool$Loader.run(Resource.java:745)
	... 1 more
	Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/bogturtle-cleaned(v1), from cache source backed by HashDirCache(http://game.havenandhearth.com/render/)
		... 4 more
		Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/bogturtle-cleaned(v1), from local res source (res)
			... 4 more
			Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/bogturtle-cleaned(v1), from local res source (res-preload)
				... 4 more
				Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/bogturtle-cleaned(v1), from filesystem res source (C:\Users\Talia\Desktop\HavenAndHearth\res)
					... 4 more
				Caused by: java.io.FileNotFoundException: gfx/invobjs/bogturtle-cleaned
					at haven.Resource$FileSource.get(Resource.java:301)
					at haven.Resource$Pool.handle(Resource.java:604)
					... 3 more
				Caused by: java.nio.file.NoSuchFileException: C:\Users\Talia\Desktop\HavenAndHearth\res\gfx\invobjs\bogturtle-cleaned.res
					at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
					at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
					at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
					at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
					at java.nio.file.Files.newByteChannel(Unknown Source)
					at java.nio.file.Files.newByteChannel(Unknown Source)
					at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
					at java.nio.file.Files.newInputStream(Unknown Source)
					at haven.Resource$FileSource.get(Resource.java:299)
					... 4 more
			Caused by: java.io.FileNotFoundException: Could not find resource locally: /res-preload/gfx/invobjs/bogturtle-cleaned.res
				at haven.Resource$JarSource.get(Resource.java:321)
				at haven.Resource$Pool.handle(Resource.java:604)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/gfx/invobjs/bogturtle-cleaned.res
			at haven.Resource$JarSource.get(Resource.java:321)
			at haven.Resource$Pool.handle(Resource.java:604)
			... 3 more
	Caused by: java.io.FileNotFoundException: res/gfx/invobjs/bogturtle-cleaned
		at haven.HashDirCache.fetch(HashDirCache.java:327)
		at haven.Resource$CacheSource.get(Resource.java:251)
		at haven.Resource$Pool.handle(Resource.java:604)
		... 3 more
Caused by: java.io.IOException: already retried 7 times
	at haven.RetryingInputStream.retry(RetryingInputStream.java:54)
	at haven.RetryingInputStream.get(RetryingInputStream.java:70)
	at haven.RetryingInputStream.check(RetryingInputStream.java:96)
	at haven.Resource$HttpSource.get(Resource.java:408)
	at haven.Resource$TeeSource.get(Resource.java:228)
	at haven.Resource$Pool.handle(Resource.java:604)
	... 3 more
Caused by: java.net.UnknownHostException: game.havenandhearth.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at haven.Resource$HttpSource$1.create(Resource.java:405)
	at haven.RetryingInputStream.create(RetryingInputStream.java:44)
	at haven.RetryingInputStream.get(RetryingInputStream.java:76)
	... 7 more

```

Please let me know if there is any additional information I can provide, such as a dxdiag of the machine encountering this issue. Thank you for your time.

**Comment by Fr-Dae** [comment]
`C:\Users\Talia\Desktop\HavenAndHearth\`
please no, not in desktop please ... make a folder in your "game" directory :cry:

**Comment by Marabellia** [comment]
> `C:\Users\Talia\Desktop\HavenAndHearth\` please no, not in desktop please ... make a folder in your "game" directory 😢

Fixed my sin and moved it to an actual folder, am still unfortunately receiving the same crash when starting Haven.

**Comment by Fr-Dae** [comment]
have you try re-download the executable ?
have you check in properties inf windows don't "block" them ?
have you java up to date ?
