### ISSUE TITLE
[BUG]crash at starting, java erro for res missing.

### ISSUE THREAD

**Issue by Fr-Dae** [EnderWiggin/hafen-client#117]
```java
haven.Resource$LoadFailedException: Failed to load resource ui/tt/q/qbuff (v7)
	at haven.Resource$Pool$Queued.get(Resource.java:559)
	at haven.Resource$Pool$Queued.get(Resource.java:526)
	at haven.Resource$CodeEntry.loader(Resource.java:1613)
	at haven.Resource$CodeEntry.loader(Resource.java:1613)
	at haven.Resource$CodeEntry.getentry(Resource.java:1639)
	at haven.Resource$CodeEntry.get(Resource.java:1671)
	at haven.Resource.getcode(Resource.java:1730)
	at haven.MenuGrid$Pagina.button(MenuGrid.java:122)
	at haven.MenuGrid$Pagina.parent(MenuGrid.java:135)
	at haven.MenuGrid.cons(MenuGrid.java:476)
	at haven.MenuGrid.consb(MenuGrid.java:444)
	at haven.MenuGrid.updlayout(MenuGrid.java:497)
	at haven.MenuGrid.tick(MenuGrid.java:684)
	at haven.Widget.tick(Widget.java:752)
	at haven.Widget.tick(Widget.java:752)
	at haven.GameUI.tick(GameUI.java:1447)
	at haven.Widget.tick(Widget.java:752)
	at haven.UI.tick(UI.java:385)
	at haven.GLPanel$Loop.run(GLPanel.java:380)
	at haven.JOGLPanel.run(JOGLPanel.java:246)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: haven.Resource$LoadException: Load error in resource ui/tt/q/qbuff(v7), from local res source (res)
	at haven.Resource$Pool.handle(Resource.java:619)
	at haven.Resource$Pool.access$1200(Resource.java:503)
	at haven.Resource$Pool$Loader.run(Resource.java:745)
	... 1 more
	Suppressed: haven.Resource$LoadException: Wrong res version (5 != 7)
		at haven.Resource.load(Resource.java:1907)
		at haven.Resource.access$700(Resource.java:44)
		at haven.Resource$Pool.handle(Resource.java:608)
		... 3 more
		Suppressed: haven.Resource$LoadException: Load error in resource ui/tt/q/qbuff(v7), from filesystem res source (/home/maevis/Games/Haven/Ender/res)
			at haven.Resource$Pool.handle(Resource.java:619)
			... 3 more
		Caused by: java.io.FileNotFoundException: ui/tt/q/qbuff
			at haven.Resource$FileSource.get(Resource.java:301)
			at haven.Resource$Pool.handle(Resource.java:604)
			... 3 more
		Caused by: java.nio.file.NoSuchFileException: /home/maevis/Games/Haven/Ender/res/ui/tt/q/qbuff.res
			at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
			at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
			at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
			at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
			at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
			at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
			at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
			at java.base/java.nio.file.Files.newInputStream(Files.java:159)
			at haven.Resource$FileSource.get(Resource.java:299)
			... 4 more
Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/ui/tt/q/qbuff.res
	at haven.Resource$JarSource.get(Resource.java:321)
	at haven.Resource$Pool.handle(Resource.java:604)
	... 3 more
```

Lubuntu 22.04x64
with openjdk-21-jre (up to date)

**Comment by Fr-Dae** [comment]
**Quickfix**
go on 
`/Games/Haven/Ender/cache/https/game.havenandhearth.com/java`
open with archive manager (7zip or whatever) 
`hafen-res.jar`
go on hafen-res.jar
copy all and past in on 

`~/Games/Haven/Ender/cache/https/enderwiggin.github.io/hafen/client-res.jar`
`/res-preload/ui/tt/q/`

**Comment by LautaroMRA02** [comment]
I don't remember if that was the order haha.

In case the same error continues, delete the cache and do the opposite of what is above, that is, let's say copy what is from enderwiggin.github.io and paste it into what is from game.havenandhearth.com

**Comment by Fr-Dae** [comment]
> I don't remember if that was the order haha.
> 
> In case the same error continues, delete the cache and do the opposite of what is above, that is, let's say copy what is from enderwiggin.github.io and paste it into what is from game.havenandhearth.com

look at the sources for your game and you'll see that it's the ender file that doesn't have the files
