### ISSUE TITLE
Unable to build from source due to issue with `polity.res`

### ISSUE THREAD

**Issue by jaggededgedjustice** [EnderWiggin/hafen-client#129]
when I attempt to build from source ant throws the following error
```
     [exec] java.lang.reflect.InvocationTargetException
     [exec] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
     [exec] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
     [exec] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
     [exec] 	at haven.Resource.loadfromdecode(Resource.java:1746)
     [exec] 	at haven.Resource.<init>(Resource.java:1606)
     [exec] 	at LayerUtil.rf(LayerUtil.java:184)
     [exec] 	at LayerUtil.main(LayerUtil.java:112)
     [exec] Caused by: java.io.FileNotFoundException: resources/src/remote/ui/polity.res/code/#CODE LAYER FOR RES custom/src/ui/polity.res/
     [exec] #String class_name
     [exec] #Note: the .class file will have the same name as this file
     [exec] haven.res.ui.polity.Generic
     [exec]  (No such file or directory)
     [exec] 	at java.base/java.io.FileInputStream.open0(Native Method)
     [exec] 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
     [exec] 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
     [exec] 	at haven.Utils.readBytes(Utils.java:471)
     [exec] 	at haven.Resource$Code.<init>(Resource.java:1064)
     [exec] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
     [exec] 	... 6 more
     [exec] Error loading file resources/src/remote/ui/polity.res
```
Although the build claims to succeed and I can run the game as long as I don't load a character that is the member of a village.
the `resources/src/remote/ui/polity.res/` directory exists and has files in it, the `code_0.data` and `code_1.data` files look basically the same as the data files in the other resource dirs. 
The `resources/src/remote/ui/polity.res/code/code_1.data` file I have contains 
```
#CODE LAYER FOR RES custom/src/ui/polity.res
#String class_name
#Note: the .class file will have the same name as this file
haven.res.ui.polity.Generic
```
the only difference between the file and `code_0.data` is `haven.res.ui.polity.GroupWidget` instead of `haven.res.ui.polity.Generic`

**Comment by EnderWiggin** [comment]
You probably are missing `resources/class` folder - try switching to beta branch and pull changes - that folder should appear and build should finish properly.

**Comment by jaggededgedjustice** [comment]
yes the `beta` branch will build
