### ISSUE TITLE
[error] thingwall preview while painting

### ISSUE THREAD

**Issue by tombabcode** [EnderWiggin/hafen-client#133]
I clicked to create a custom paint sketch, uploaded image and selected "Thingwall" in the sketch preview, got crash below. Restarting the game didn't help, cause "Thingwall" is still selected, and error occured again. Cannot even change it to different preview, thus, I'm unable to create custom pain sketches now. Run on Steam Ender's client

```
haven.Resource$LoadFailedException: Failed to load resource gfx/terobjs/thingwall (v12)
	at haven.Resource$Pool$Queued.get(Resource.java:586)
	at haven.Resource$Pool$Queued.get(Resource.java:553)
	at haven.Resource$Spec.get(Resource.java:118)
	at haven.Resource$Spec.get(Resource.java:122)
	at haven.Resource$Spec.get(Resource.java:105)
	at haven.DynresWindow$Preview$Spec.create(DynresWindow.java:644)
	at haven.DynresWindow$Preview$View.tick(DynresWindow.java:719)
	at haven.Widget.tick(Widget.java:785)
	at haven.Widget$TickEvent.shandle(Widget.java:927)
	at haven.Widget.handle(Widget.java:907)
	at haven.Widget$Event.dispatch(Widget.java:860)
	at haven.Widget$TickEvent.propagation(Widget.java:920)
	at haven.Widget$Event.propagate(Widget.java:850)
	at haven.Widget$Event.dispatch(Widget.java:862)
	at haven.Widget$TickEvent.propagation(Widget.java:920)
	at haven.Widget$Event.propagate(Widget.java:850)
	at haven.Widget$Event.dispatch(Widget.java:862)
	at haven.Widget$TickEvent.propagation(Widget.java:920)
	at haven.Widget$Event.propagate(Widget.java:850)
	at haven.Widget$Event.dispatch(Widget.java:862)
	at haven.Widget$TickEvent.propagation(Widget.java:920)
	at haven.Widget$Event.propagate(Widget.java:850)
	at haven.Widget$Event.dispatch(Widget.java:862)
	at haven.Widget$TickEvent.propagation(Widget.java:920)
	at haven.Widget$Event.propagate(Widget.java:850)
	at haven.Widget$Event.dispatch(Widget.java:862)
	at haven.UI.dispatch(UI.java:641)
	at haven.UI.tick(UI.java:401)
	at haven.GLPanel$Loop.run(GLPanel.java:376)
	at haven.JOGLPanel.run(JOGLPanel.java:246)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Wrong res version (13 != 12)
	at haven.Resource.load(Resource.java:1931)
	at haven.Resource.access$600(Resource.java:44)
	at haven.Resource$Pool.handle(Resource.java:643)
	at haven.Resource$Pool.access$1100(Resource.java:530)
	at haven.Resource$Pool$Loader.run(Resource.java:784)
	... 1 more
	Suppressed: haven.Resource$LoadException: Wrong res version (13 != 12)
		... 6 more
		Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/thingwall(v12), from local res source (res)
			at haven.Resource$Pool.handle(Resource.java:654)
			... 3 more
			Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/thingwall(v12), from local res source (res-preload)
				... 4 more
				Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/thingwall(v12), from filesystem res source (C:\Users\conta\AppData\Roaming\Haven and Hearth\ender-client\res)
					... 4 more
				Caused by: java.io.FileNotFoundException: gfx/terobjs/thingwall
					at haven.Resource$FileSource.get(Resource.java:365)
					at haven.Resource$Pool.handle(Resource.java:631)
					... 3 more
				Caused by: java.nio.file.NoSuchFileException: C:\Users\conta\AppData\Roaming\Haven and Hearth\ender-client\res\gfx\terobjs\thingwall.res
					at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
					at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
					at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
					at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
					at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
					at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
					at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
					at java.base/java.nio.file.Files.newInputStream(Unknown Source)
					at haven.Resource$FileSource.get(Resource.java:363)
					... 4 more
			Caused by: java.io.FileNotFoundException: Could not find resource locally: /res-preload/gfx/terobjs/thingwall.res
				at haven.Resource$JarSource.get(Resource.java:385)
				at haven.Resource$Pool.handle(Resource.java:631)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/gfx/terobjs/thingwall.res
			at haven.Resource$JarSource.get(Resource.java:385)
			at haven.Resource$Pool.handle(Resource.java:631)
			... 3 more
```

**Comment by EnderWiggin** [comment]
loftar says he fixed this with latest update. Re-open if this still happens.
