### ISSUE TITLE
Building and Running

### ISSUE THREAD

**Issue by SaintPepsi** [EnderWiggin/hafen-client#136]
I tried to follow the instructions in the `README` file;
I ran `ant bin -buildfile build.xml` from the project folder - The build would succeed after 40 seconds
then I run `java -jar bin/hafen.jar` from the project folder, and then I get an error.

Am I missing something as part of getting the client running?

The Error:
```
java.lang.Error: java.lang.reflect.InvocationTargetException
	at haven.MainFrame.javabughack(MainFrame.java:413)
	at haven.MainFrame.main2(MainFrame.java:431)
	at haven.MainFrame.lambda$main$0(MainFrame.java:478)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at haven.MainFrame.javabughack(MainFrame.java:404)
	... 3 more
Caused by: java.lang.ExceptionInInitializerError
	at haven.MainFrame$5.run(MainFrame.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "haven.Resource$Image.tex()" because the return value of "haven.Resource.loadrimg(String)" is null
	at haven.Resource.loadtex(Resource.java:1983)
	at haven.LoginScreen.<clinit>(LoginScreen.java:39)
	... 14 more
```

**Comment by Clownvin** [comment]
I was also having this issue while trying to run. Eventually I switched over to my Windows machine, and using IntelliJ and a 1.8 JDK, the problem went away. I have yet to test it on my Linux machine, but I suspect the main difference was using 1.8 rather than the latest JDK.

Basically, I just set everything that cared about it to 1.8, and then ran the "run" ant command (might have had to run a few other commands to make "run" work, but that's the jist).
