### ISSUE TITLE
[issue] crash while eating

### ISSUE THREAD

**Issue by tombabcode** [EnderWiggin/hafen-client#138]
I was just eating from the table and sudden crash occured

```
java.lang.NullPointerException: Cannot invoke "haven.Indir.get()" because "this.trev" is null
	at haven.BAttrWnd$FoodMeter.lambda$tick$0(BAttrWnd.java:363)
	at haven.Loader.lambda$defer$0(Loader.java:240)
	at haven.Loader$Future.run(Loader.java:71)
	at haven.Loader$Future.access$400(Loader.java:42)
	at haven.Loader.loop(Loader.java:202)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by EnderWiggin** [comment]
was caused by recent loftar's change - fixed
