### ISSUE TITLE
Client crash when New Character pressed

### ISSUE THREAD

**Issue by MrROBUST** [EnderWiggin/hafen-client#25]
strace:
```
java.lang.IllegalStateException: MappingClient should be initialized first!
	at integrations.mapv4.MappingClient.getInstance(MappingClient.java:54)
	at haven.GameUI.addchild(GameUI.java:948)
	at haven.UI.newwidget(UI.java:246)
	at haven.RemoteUI.run(RemoteUI.java:65)
	at haven.MainFrame.uiloop(MainFrame.java:286)
	at haven.MainFrame.run(MainFrame.java:302)
	at haven.MainFrame.main2(MainFrame.java:448)
	at haven.MainFrame.lambda$main$0(MainFrame.java:484)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
config.json:
```
{
  "general": {
    "storemap": true,
    "start_toggle": {
      "tracking": true
    },
    "toolbelt1": true,
    "warning": {
      "animal": {
        "highlight": true,
        "message": true
      }
    }
  },
  "ui": {
    "menu_add_pick_all": true,
    "progress_number": true,
    "real_time_curio": true,
    "show_curio_lph": true
  },
  "automap": {
    "upload": true,
    "track": false
  },
  "display": {
    "gob_paths": {
      "show": true,
      "categories": [
        "FOE",
        "ME",
        "AGGRESSIVE_ANIMAL"
      ]
    },
    "show_gob_radius": true
  },
  "version": "06.04.2021 20:14"
}
```

**Comment by MrROBUST** [comment]
Making `"upload": false` for `"automap"` allows to play fine.
