### ISSUE TITLE
crach when i clic on "carpentery" skill (maybe FR issue)

### ISSUE THREAD

**Issue by Fr-Dae** [EnderWiggin/hafen-client#68]
it's maybe my FR translation need some fix
do I need to convert all accesses to UTF8 like
"%C3%A9" or "&eacute;" &eacute; for "é" 
or does the problem come from somewhere else? 

```js
haven.RichText$FormatException: Junk left after the end of input: 

	at haven.RichText$Parser.parse(RichText.java:561)
	at haven.RichText$Parser.parse(RichText.java:573)
	at haven.RichText$Parser.parse(RichText.java:583)
	at haven.RichText$Foundry.render(RichText.java:737)
	at haven.RichTextBox.settext(RichTextBox.java:61)
	at haven.CharWnd$LoadingTextBox.draw(CharWnd.java:741)
	at haven.Widget.draw(Widget.java:776)
	at haven.Widget.draw(Widget.java:781)
	at haven.Widget.draw(Widget.java:776)
	at haven.Widget.draw(Widget.java:781)
	at haven.Widget.draw(Widget.java:776)
	at haven.Widget.draw(Widget.java:781)
	at haven.GameUI.draw(GameUI.java:1264)
	at haven.Widget.draw(Widget.java:776)
	at haven.Widget.draw(Widget.java:781)
	at haven.RootWidget.draw(RootWidget.java:123)
	at haven.UI.draw(UI.java:248)
	at haven.GLPanel$Loop.display(GLPanel.java:312)
	at haven.GLPanel$Loop.run(GLPanel.java:401)
	at haven.JOGLPanel.run(JOGLPanel.java:246)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Fr-Dae** [comment]
any commentary about modification ?
