### ISSUE TITLE
[BUG]crash with tree

### ISSUE THREAD

**Issue by Fr-Dae** [EnderWiggin/hafen-client#93]
on Lubuntu 22.04, with openjdk-21
after exit on my home, sometime, game crash

```js
haven.render.RenderTree$SlotRemoved
	at haven.render.RenderTree$TreeSlot.chstate(RenderTree.java:677)
	at haven.render.RenderTree$TreeSlot.ostate(RenderTree.java:709)
	at haven.res.lib.flare.AnimFlare.autotick(flare.cjava:170)
	at haven.render.TickList.lambda$tick$0(TickList.java:135)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
![Capture d’écran du 2023-12-23 12-03-31](https://github.com/EnderWiggin/hafen-client/assets/23202421/b525a7d0-c302-4b16-a725-b305e4fe8fca)

**Comment by Dropbeard** [comment]
I've had the same; it only seems to happen (at least usually) if I have trees hidden or if I try to hide trees. With trees visible, I don't get the crash. It started when the christmas ornaments appeared on trees, so might be something related to those.
